name: Say goodbye

on:
  push:
    branches:
      - main

jobs:
  hello_world: 
    runs-on: ubuntu-22.04
    steps:
      - name: Display the message
        run: echo "Hello and goodbye, using ubuntu-22.04"
      - name: Display the date
        run: date
      - run: la 
